"""added assignee id to tasks

Revision ID: 4603273539f5
Revises: 7e2001cdce8c
Create Date: 2026-06-20 03:04:25.132745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4603273539f5'
down_revision: Union[str, Sequence[str], None] = '7e2001cdce8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assignee_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'assignee_id')
    # ### end Alembic commands ###
